<a href="https://colab.research.google.com/github/connectasp/Numpy_Task/blob/main/Numpy_tasks_IITM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)

1.21.6


In [8]:
print(np.show_config())

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [10]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [11]:
print(a.size)

10


In [12]:
print(a.itemsize)

8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

In [15]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [16]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [18]:
b = np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [26]:
c = b[::-1]
print(c)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [25]:
d = np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [27]:
a = np.array([1,2,0,0,4,0])
b = np.nonzero(a)
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [28]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [31]:
a = np.random.rand(3,3,3)
print(a)

[[[5.63938875e-01 7.39324062e-01 5.70819115e-01]
  [1.27381642e-02 8.73998245e-01 7.81004598e-01]
  [2.38919046e-01 2.73405602e-01 7.13910818e-01]]

 [[2.29581796e-01 2.30495488e-01 4.03930639e-01]
  [5.25422131e-02 4.58165276e-01 9.22081092e-01]
  [1.47724089e-01 7.99532687e-01 7.01425300e-01]]

 [[3.54057043e-04 5.20580837e-01 3.45985800e-02]
  [7.14346649e-01 1.24924105e-01 6.60131542e-01]
  [4.06365138e-01 1.32093908e-01 5.16556461e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [38]:
a = np.random.randint(100,size=(10,10))
print(a)


[[77 23 80 60 49 89 93 10 86 83]
 [96 65 52 83 21 66 71 58 11 96]
 [74 74 78 39 81 82 25 71 16  1]
 [30 36 51 62 34 23 80 65  2 23]
 [71 97  8 54 45 43 53 85 81 16]
 [74 76 93 55 67 15 48 10 39 35]
 [72 40 45 88 36 44 51 89 28 49]
 [94 18  9 53 42 93 59 81 14 59]
 [50 49 52  3 69 96 91 98 42 69]
 [64 29 43  0 30 30 68 12 61 93]]


In [41]:
b = np.min(a)
print(b)

0


In [42]:
c = np.max(a)
print(c)

98


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [47]:
a = np.random.randint(100,size=(30))
print(a)

[98 31 17 29 10 93 18 31 78 15 69 31 19 20 22 64 89 97 56 41  4 53 46 61
 51 46 65  8 31 34]


In [48]:
b = np.mean(a)
print(b)

44.233333333333334


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [50]:
c = np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
c[1:-1,1:-1]=0
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [53]:
c = np.pad(c, pad_width=1, mode='constant', constant_values=0)
print(c)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [54]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [55]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [56]:
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [57]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [58]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [59]:
a = np.random.random((5,5))
a_max, a_min = a.max(), a.min()
a = (a - a_min)/(a_max - a_min)
print(a)

[[0.24528889 0.27181014 0.36846451 0.37737586 0.93466691]
 [1.         0.64543472 0.96721584 0.34002274 0.17528035]
 [0.         0.68533127 0.35779539 0.40428695 0.12758992]
 [0.59292403 0.55650504 0.14646165 0.68797683 0.36893309]
 [0.91583259 0.55542614 0.71073776 0.83081712 0.79987307]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [67]:
c = np.dtype([("r", np.ubyte, (1,)), ("g", np.ubyte, (1,)), ("b", np.ubyte, (1,)), ("a", np.ubyte, (1,))])
print(c)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [68]:
d = np.dot(np.ones((5,3)), np.ones((3,2)))
print(d)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [70]:
a = np.arange(11)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [71]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [72]:
a = np.ones(5)
print(a**a)

[1. 1. 1. 1. 1.]


In [78]:
b = (a <- a)
print(b)

[False False False False False]


In [79]:
print(1j*a)

[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]


In [80]:
print(a/1/1)

[1. 1. 1. 1. 1.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [83]:
a = np.array(0) / np.array(0)
print(a)

nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [84]:
b = np.array(0) // np.array(0)
print(b)

0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [85]:
c = np.array([np.nan]).astype(int).astype(float)
print(c)

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [86]:
a = np.random.uniform(-10,+10,10)
print (np.trunc(a + np.copysign(0.5, a)))

[-6.  5. -6. -8. -6.  9.  2.  2.  1. -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [88]:
a = np.random.randint(0,20,20)
b = np.random.randint(0,20,20)
print(a, b)


[19  6  6  9 16  9  0 15  8 14  2  7  3  0  2  5 16 12 17 16] [13 13 16  6  3 14 19 15  4 12  7  4 11 19  3 17  8 19  6 12]


In [89]:
print(np.intersect1d(a,b))

[ 3  6  7  8 12 14 15 16 17 19]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [91]:
defaults = np.seterr(all="ignore")
a = np.ones(1) / 0
a

array([inf])

In [95]:
b = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0
b

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [96]:
a =(np.sqrt(-1) == np.emath.sqrt(-1))
a

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [97]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today = np.datetime64('today')
print(today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2022-11-13
2022-11-14
2022-11-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [98]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [99]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [101]:
a = np.random.uniform(0,10,3)
print(a)


[0.94238193 3.61883955 4.04261418]


In [104]:
print(np.floor(a))


[0. 3. 4.]


In [105]:
print(np.ceil(a))

[1. 4. 5.]


In [106]:
print(a.astype(int))


[0 3 4]


In [107]:
print(np.trunc(a))

[0. 3. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [109]:
b = np.zeros((5,5))
b += np.arange(5)
print(b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [110]:
def generate():
  for x in range(10):
    yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [111]:
b = np.linspace(0,1,11,endpoint=False)[1:]
print(b)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [112]:
b = np.random.random(10)
b.sort()
print(b)

[0.06096872 0.07137753 0.22953839 0.3097178  0.31373996 0.31738351
 0.53858569 0.80609615 0.81807496 0.85479434]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [113]:
c = np.arange(10)
np.add.reduce(c)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [114]:
A = np.random.randint(0,3,4)
B = np.random.randint(0,3,4)
print(A, B)

[0 1 1 2] [1 1 0 0]


In [115]:
e = np.allclose(A,B)
print(e)

False


In [116]:
e = np.array_equal(A,B)
print(e)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [117]:
a = np.zeros(10)
a.flags.writeable = False
try:
    a[0] = 1
except Exception as e:
    print(e)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [118]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
b = np.sqrt(x**2+y**2)
print(b)


[0.33323907 0.32157256 0.97451131 0.94663266 0.51541878 0.48492617
 0.15608359 0.8676539  0.60306258 0.96788327]


In [119]:
c = np.arctan2(y,x)
print(c)

[0.14390458 1.05350623 0.21974656 0.11973853 0.85550903 0.0424599
 1.19322635 0.8979136  1.02261025 1.28883286]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [120]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.         0.62810818 0.77057839 0.6552624  0.26354837 0.24376903
 0.19971954 0.79994039 0.70414187 0.7337817 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [122]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [123]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [124]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [125]:
for dtype in [np.float32, np.float64]:
 print(np.finfo(dtype).min)
 print(np.finfo(dtype).max)
 print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [126]:
np.set_printoptions(threshold=float("inf"))
a = np.random.random((4,4))
print(a)

[[0.51621701 0.62175513 0.92878449 0.89865929]
 [0.37514109 0.98948266 0.99888263 0.64954027]
 [0.94838919 0.97084275 0.52619203 0.09786381]
 [0.71743737 0.53241826 0.60683735 0.69841938]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [127]:
a = np.arange(100)
b = np.random.uniform(0,100)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

71.38339879407062
71


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [128]:
a = (np.random.rand(3)*100).astype(np.float32)
print(a)
b = a.view(np.int32)
b[:] = a
print(b)
print(b.base is a)

[86.90359 80.43896  6.16967]
[86 80  6]
True


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [130]:
from io import StringIO
a = StringIO('''1, 2, 3, 4, 56,  ,  , 7, 8,  , 9,10,11''')
b = np.genfromtxt(a, delimiter=",", dtype=int)
print(b)

[ 1  2  3  4 56 -1 -1  7  8 -1  9 10 11]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [131]:
a = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(a):
  print(index, value)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [133]:
for x in np.ndindex(a.shape):
  print(x, a[x])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [134]:
a, b = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,5))
c = np.sqrt(a*a+b*b)
sigma, mu = 1.0, 0.0
d = np.exp(-( (c-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(d.shape)
print(d)

(5, 4)
[[0.36787944 0.57375342 0.57375342 0.36787944]
 [0.53526143 0.8348063  0.8348063  0.53526143]
 [0.60653066 0.94595947 0.94595947 0.60653066]
 [0.53526143 0.8348063  0.8348063  0.53526143]
 [0.36787944 0.57375342 0.57375342 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [137]:
n = 10
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [138]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-0.31161803,  0.22624492,  0.17824065,  0.1345089 ,  0.17892025,
         0.41360896, -0.43501107, -0.38218659, -0.32951346,  0.32680546],
       [-0.06049354, -0.19321756,  0.24463049,  0.18282195,  0.11270236,
        -0.55467951,  0.28608895, -0.19385523,  0.29187822, -0.11587613],
       [-0.22217368,  0.07751075,  0.17509335,  0.18118737, -0.24623572,
         0.29338329, -0.07815461, -0.19531014,  0.1396101 , -0.12491072],
       [-0.32932122, -0.12553928,  0.13160818, -0.30867016, -0.49046841,
         0.44838024,  0.28003508, -0.20126883,  0.32442307,  0.27082133],
       [ 0.30983054,  0.35259919, -0.01855711, -0.20366075,  0.05257512,
         0.19060461, -0.0551055 , -0.16185813,  0.09257275, -0.55900072]])

In [140]:
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.31161803,  0.22624492,  0.17824065,  0.1345089 ,  0.17892025,
         0.41360896, -0.43501107, -0.38218659, -0.32951346,  0.32680546],
       [-0.06049354, -0.19321756,  0.24463049,  0.18282195,  0.11270236,
        -0.55467951,  0.28608895, -0.19385523,  0.29187822, -0.11587613],
       [-0.22217368,  0.07751075,  0.17509335,  0.18118737, -0.24623572,
         0.29338329, -0.07815461, -0.19531014,  0.1396101 , -0.12491072],
       [-0.32932122, -0.12553928,  0.13160818, -0.30867016, -0.49046841,
         0.44838024,  0.28003508, -0.20126883,  0.32442307,  0.27082133],
       [ 0.30983054,  0.35259919, -0.01855711, -0.20366075,  0.05257512,
         0.19060461, -0.0551055 , -0.16185813,  0.09257275, -0.55900072]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [141]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[1 1 9]
 [7 0 7]
 [1 9 3]]
[[7 0 7]
 [1 1 9]
 [1 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [142]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [143]:
a = np.random.uniform(0,1,10)
b = 0.5
m = a.flat[np.abs(a - b).argmin()]
print(m)

0.547405127475515


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [152]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj  

  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', "no name")

a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [153]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[4. 3. 6. 5. 1. 2. 2. 3. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [155]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [156]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [157]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[64 65 61 47]
 [59 60 65 42]
 [44 57 68 58]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [158]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.46620767 0.55671384 0.46983314 0.45644524 0.46132791 0.41540556
 0.57748601 0.44717083 0.56432909 0.51925494]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [166]:
a = np.array([[3, 7],[9, 10]])
b = np.array([[4, 8],[9, 10]])
c = np.diag(np.dot(a, b))
print(c)

[ 75 172]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [167]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [168]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [169]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [170]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 12) ( 2, 58) ( 4, 80) ( 4, 88) ( 7, 21) ( 7, 34) ( 7, 44) ( 7, 56)
 (12, 58) (21, 44) (29, 73) (29, 91) (32, 59) (32, 72) (34, 56) (40, 79)
 (40, 83) (57, 69) (57, 76) (59, 72) (69, 76) (69, 84) (70, 78) (70, 97)
 (73, 91) (76, 84) (78, 97) (79, 83) (80, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [171]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [172]:
def moving_average(a, n=3) :
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [173]:
from numpy.lib import stride_tricks
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [177]:
z = np.random.randint(0,2,100)
np.logical_not(z, out=z)
print(z)
z = np.random.uniform(-1.0,1.0,100)
np.negative(z, out=z)
print(z)

[1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1
 0 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1
 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0]
[-0.265148    0.84258186  0.14967865 -0.4431844  -0.9272548  -0.62461444
  0.43682357  0.36978733  0.51393875  0.343943   -0.58180643 -0.44330778
 -0.11843648 -0.63733911 -0.58158772  0.43230698  0.71947457 -0.37077249
  0.85289539  0.3042128   0.96418317 -0.38262189 -0.70129896  0.46101797
 -0.5657777  -0.75336401  0.98652636 -0.37244908 -0.30516651 -0.0444458
  0.24344403 -0.45314074 -0.40097896 -0.49440862  0.36708957  0.07982605
 -0.69547116  0.68322214  0.41341923  0.74850068  0.34307468  0.67555763
 -0.67226488 -0.08259434  0.79376551  0.98386698 -0.17275519 -0.18837098
 -0.99120528  0.61764222 -0.4161445   0.06898416 -0.52560092  0.67047269
  0.02543996  0.25022487  0.93456077 -0.879499   -0.93035788 -0.52259024
 -0.33777321 -0.18695339 -0.63143616 -0.79455126  0.89774127 -0.577

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [178]:
def distance(P0, P1, p):
  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.43610047  1.72106292  5.15486478 12.47680272  9.63734073  3.24387329
 14.21333659  7.63926295  5.78354849 14.10612919]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [180]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.04419965  8.23704551  4.61487043  8.62448391  4.9557145   1.31992094
  14.15610321  2.82238699  5.64045013  8.95983184]
 [ 3.94229694  0.92522366  5.71461652  1.3338379   5.25047269  5.42701038
   4.51252979  5.22906686  3.11733554  1.45840541]
 [ 5.27122119  9.52669139  5.67355303  9.97968172  5.67053224  2.67304209
  14.64771684  2.92063365  6.95804144  9.85798722]
 [ 2.70386856  1.90173456  3.22532011  4.1641371   3.375651    2.63302619
   5.95951561  4.57214769  0.26532981  0.75281997]
 [ 3.61728468 10.44296336  6.01719201 11.28257621  5.43238024  4.05141744
  14.10213028  1.92061257  7.98189916  9.90874128]
 [12.38278712  4.86179647  3.43999475  3.74931576  5.99912339  3.85043198
  16.36514981  6.74438439  1.84935282  8.90367443]
 [ 7.03948336 12.10349276  9.01392467 11.6677807   9.3358166   4.12622864
  18.31337465  6.32493827  9.32760726 13.41386767]
 [11.07389497  3.19624356  1.21952849  2.70926914  3.51795025  4.72707953
  13.86137545  4.38325869  0.33092816  6.51704744]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [181]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 8 0 8 5 8 7 6 1 3]
 [4 9 4 3 6 4 8 7 5 4]
 [2 7 8 9 1 1 8 4 7 5]
 [3 3 6 4 7 9 4 9 7 6]
 [8 6 2 2 8 3 5 0 2 8]
 [1 4 0 6 4 0 5 8 0 5]
 [2 6 7 1 0 9 4 9 4 9]
 [6 3 3 6 3 8 1 0 7 1]
 [2 3 1 4 4 5 3 4 5 2]
 [2 5 6 4 2 9 6 5 8 7]]
[[0 0 0 0 0]
 [0 0 8 0 8]
 [0 4 9 4 3]
 [0 2 7 8 9]
 [0 3 3 6 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [182]:
a = np.arange(1,15,dtype=uint32)
b = stride_tricks.as_strided(a,(11,4),(4,4))
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)